scss_files: 'app/assets/stylesheets/application/**/*.*css'

linters:
  BangFormat:
    enabled: true
  BorderZero:
    enabled: true
  ColorKeyword:
    enabled: true
  ColorVariable:
    enabled: true
  Comment:
    enabled: true
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: false
  DisableLinterReason:
    enabled: true
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: true
  EmptyRule:
    enabled: true
  ExtendDirective:
    enabled: true
  FinalNewline:
    enabled: true
  HexLength:
    enabled: true
    style: long
  HexNotation:
    enabled: true
  HexValidation:
    enabled: true
  IdSelector:
    enabled: true
  ImportantRule:
    enabled: true
  ImportPath:
    enabled: true
  Indentation:
    enabled: true
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: true
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: true
  PropertySortOrder:
    enabled: true
  PropertySpelling:
    enabled: true
  PropertyUnits:
    enabled: true
    global: ['rem', 'em', '%']
    properties:
      animation: ['s', 'ms']
      animation-duration: ['s', 'ms']
      border: ['rem', 'em', 'px']
      border-radius: ['rem', 'em', '%', 'px']
      border-top-width: ['rem', 'em', 'px']
      border-width: ['rem', 'em', 'px']
      font-size: ['em', 'rem', 'px', 'vw', '%']
      height: ['rem', 'em', '%', 'px', 'vh']
      max-height: ['rem', 'em', '%', 'px', 'vh']
      min-height: ['rem', 'em', '%', 'px', 'vh']
      max-width: ['rem', 'em', '%', 'px', 'vw']
      min-width: ['rem', 'em', '%', 'px', 'vw']
      transition: ['s', 'ms']
      transition-duration: ['s', 'ms']
      width: ['rem', 'em', '%', 'px', 'vw']
  PseudoElement:
    enabled: true
  QualifyingElement:
    enabled: true
  SelectorDepth:
    enabled: true
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
  Shorthand:
    enabled: true
  SingleLinePerProperty:
    enabled: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterVariableName:
    enabled: true
  SpaceAroundOperator:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
    style: double_quotes
  TrailingSemicolon:
    enabled: true
  TrailingWhitespace:
    enabled: true
  TrailingZero:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlQuotes:
    enabled: true
  VendorPrefix:
    enabled: true
  ZeroUnit:
    enabled: true
